apiVersion: mysql.oracle.com/v2alpha1
kind: InnoDBCluster
metadata:
  name: cno-api-mysql
spec:
  secretName: cno-api-db-secret
  instances: 1
  router:
    instances: 1
---

#apiVersion: v1
#kind: Secret
#metadata:
#  name: mypwds
#stringData:
#  rootUser: root
#  rootHost: '%'
#  rootPassword: MySQL202!