# create namespace for keycloak template
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: sso
spec:
  instances: 1
  extensions:
    - https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  externalAccess:
    enabled: False
    tlsTermination: passthrough
  podDisruptionBudget:
    enabled: True
  profile: RHSSO
  externalDatabase:
    enabled: True
  keycloakDeploymentSpec:
    experimental:
      args:
        - "-Djboss.as.management.blocking.timeout=600"
      env:
        - name: PROXY_ADDRESS_FORWARDING
          value: "false"
        - name: DB_ADDR
          value: postgres-headless-svc.cno-system.svc.cluster.local
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: postgres
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USERNAME
              name: keycloak-db-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: keycloak-db-secret
      volumes:
        items:
        - name: cno-realm
          mountPath: /cno
          configMaps:
            - cno-realm
      env:
        - name: KEYCLOAK_IMPORT
          value: /cno/cno-realm.json







