# create namespace for keycloak template
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: cloud-keycloak
  labels:
    app: sso
spec:
  instances: 1
  externalAccess:
    enabled: false
    tlsTermination: passthrough
  podDisruptionBudget:
    enabled: True
  externalDatabase:
    enabled: True
  keycloakDeploymentSpec:
    experimental:
      args:
        - "-Djboss.as.management.blocking.timeout=600"
        - "-Djava.net.preferIPv4Stack=true"
      volumes:
        items:
        - name: cno-realm
          mountPath: /cno
          configMaps:
            - cno-realm
      env:
        - name: KEYCLOAK_IMPORT
          value: /cno/cno-realm.json



